language: php
sudo: required
php:
    - 7.4
    - 8.0
    - 8.1
    - nightly
env:
    - XDEBUG_MODE=coverage
before_install:
    - curl -s http://getcomposer.org/installer | php
    # Fix Argon2i password hasher in TravisCi PHP version
    - composer require paragonie/sodium_compat
install:
    - php composer.phar install --dev --no-interaction
script:
    - vendor/bin/phpcs --report=full -p ./src
    - vendor/bin/phpstan analyse -c phpstan.neon
    - vendor/bin/atoum -d tests
jobs:
    allow_failures:
        -   php: nightly
