language: php
sudo: required
php:
    - 7.3
    - 7.4
    - 8.0
    - nightly
env:
    - XDEBUG_MODE=coverage
before_install:
    - curl -s http://getcomposer.org/installer | php
    # Fix Argon2i password hasher in TravisCi PHP version
    - composer require paragonie/sodium_compat
install:
    - php composer.phar install --dev --no-interaction
script:
    - vendor/bin/phpcs --report=full --report-file=./report.txt --extensions=php --warning-severity=0 --standard=PSR2 -p ./src
    - vendor/bin/phpstan analyse -l max src
    - vendor/bin/atoum -d tests
jobs:
    allow_failures:
        -   php: 7.3 # Travis fails to enable sodium
        -   php: 8.0
        -   php: nightly
